name = "shidduchdashboard"
compatibility_date = "2026-09-01"
main = "worker.js"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "shidduch-ledger-db"
database_id = "b7c0fb62-eb26-425a-8a2f-21114cce40a7"

[[r2_buckets]]
binding = "RESUMES"
bucket_name = "shidduch-ledger-files"

[ai]
binding = "AI"
